# Generated by Django 2.2.3 on 2019-08-20 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20190820_0918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryItem',
        ),
    ]
