# Generated by Django 2.2.3 on 2019-08-23 03:49

from django.db import migrations, models
import item.models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_auto_20190820_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(related_name='items', to='item.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=item.models.get_item_image_path),
        ),
    ]
