# Generated by Django 2.2.3 on 2019-08-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20190823_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(related_name='items', to='item.Category'),
        ),
    ]
